### ISSUE TITLE
flysystem-cached-extra should not be separate library

### ISSUE THREAD

**Issue by Bilge** [nao-pon/flysystem-google-drive#33]
It seems `nao-pon/flysystem-cached-extra` has a 1:1 relationship with this library and [no other dependants](https://packagist.org/packages/nao-pon/flysystem-cached-extra/dependents). A separate library should be created only when there is a case for code reuse, but it seems the library exists solely to serve this repository. Ergo, it should not be a separate library at all. The few files it has should be reintegrated with this project instead of hanging out in another repository, fragmenting the codebase without benefit.

---

Aside, despite its name, it seems that library has nothing to do with caching, either.

**Comment by nao-pon** [comment]
@Bilge  nao-pon/flysystem-cached-extra was created to make the cache mechanism work properly when using [Studio-42/elFinder](https://github.com/Studio-42/elFinder) + [barryvdh/elfinder-flysystem-driver](https://github.com/barryvdh/elfinder-flysystem-driver). And because there is a possibility that it can be used with other adapters, it is independent.
